name: 'sales_project'
version: '1.0.0'
config-version: 2

profile: 'sales_project'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"


models:
  sales_project:
    +materialized: table  